const routes = require('next-routes')

module.exports = routes()
    .add('/', 'index')
    .add('/especialidades', 'especialidades')
    .add('/especialidades/portfolio', 'portfolio')
    .add('/especialidades/entrevistas', 'entrevistas')
    .add('/especialidades/:id', 'especialidade')
    .add('/materiais', 'materiais')
    .add('/painel', 'painel')
    .add('/experiencias', 'experiencias')
    .add('/experiencias/:id', 'experiencia')
    .add('/dicas', 'dicas')
    .add('/casos_clinicos', 'casosclinicos')
    .add('/especializacao_e_cursos', 'especializacaoecursos')