const routes = require('next-routes')

module.exports = routes()
    .add('/especialidades', 'especialidades')
    .add('/especialidades/portfolio', 'portfolio')
    .add('/especialidades/entrevistas', 'entrevistas')
    .add('/especialidades/:id', 'especialidade')
    .add('/materiais', 'materiais')
    .add('/painel', 'painel')
    .add('/galeria', 'galeria')
    .add('/dicas', 'dicas')
    .add('/casos_clinicos', 'casosclinicos')
    .add('/especializacao_e_cursos', 'especializacaoecursos')
    .add('/', 'home')